import { createVuetify } from 'vuetify';
import 'vuetify/styles';
import '@mdi/font/css/materialdesignicons.css';
import {
    VImg,
    VBtn,
    VCard,
    VTextField,
    VCardText,
    VIcon,
    VAlert,
    VSlideXReverseTransition,
    VSelect,
    VSheet,
    VDivider,
    VToolbar,
    VApp,
    VAppBar,
    VSpacer,
    VMain,
    VContainer,
    VMenu,
    VList,
    VSwitch,
    VCardActions,
    VListItem,
    VAppBarNavIcon,
    VListItemTitle,
    VToolbarTitle,
    VLayout,
    VNavigationDrawer,
    VTabs,
    VTabsWindow,
    VTabsWindowItem,
    VTab,
    VBreadcrumbs,
    VRow,
    VCol,
    VSlider,
    VAvatar,
    VDataTableServer,
    VDataTableHeaders,
    VExpansionPanel,
    VExpansionPanels,
    VExpansionPanelText,
    VExpansionPanelTitle,
    VDialog,
    VTextarea,
    VTooltip,
    VCardTitle,
    VChip,
    VBreadcrumbsItem,
    VDataTable,
    VDataTableVirtual,
    VProgressLinear
} from 'vuetify/components';
import { VCalendar, VTimePicker } from 'vuetify/lib/labs/components.mjs';

export default createVuetify({
    components: {
        VImg,
        VBtn,
        VCard,
        VTextField,
        VCardText,
        VIcon,
        VAlert,
        VSlideXReverseTransition,
        VSelect,
        VSheet,
        VDivider,
        VToolbar,
        VApp,
        VAppBar,
        VSpacer,
        VMain,
        VContainer,
        VMenu,
        VList,
        VSwitch,
        VCardActions,
        VListItem,
        VAppBarNavIcon,
        VListItemTitle,
        VToolbarTitle,
        VLayout,
        VNavigationDrawer,
        VTab,
        VTabs,
        VTabsWindow,
        VTabsWindowItem,
        VBreadcrumbs,
        VBreadcrumbsItem,
        VRow,
        VCol,
        VSlider,
        VAvatar,
        VDataTableServer,
        VDataTableHeaders,
        VExpansionPanel,
        VExpansionPanels,
        VExpansionPanelText,
        VExpansionPanelTitle,
        VDialog,
        VTextarea,
        VTooltip,
        VCardTitle,
        VCalendar,
        VChip,
        VTimePicker,
        VDataTable,
        VDataTableVirtual,
        VProgressLinear
    },
    icons: {
        defaultSet: 'mdi', // Establece Material Design Icons como el set de iconos por defecto
    },
});
